### PR TITLE
No really: reliable force-quit/idle.

### PR DESCRIPTION
**Pull request by aaronklaassen**
⚠️ in progress

- [x] better AHK
  - fuckin' serious about force-quitting an idle/crashed game
  - check that a game has quit and exit the AHK script too (fixes lag between game-quit and back-to-menu)
- [ ] ~~*maybe this pr?* The AHK templates are really repetitive (e.g. the only difference between legacy and default is the key map), so it'd be nice to do some `include`s or something to DRY it up.~~

### CODE REVIEW

**Comment by mrmwiebe** [comment]
Awwwwww HELL yea.  Will test sometime today (hopefully)

**Comment by mrmwiebe** [comment]
Unless you're already working on it, don't worry about drying it up yet.  If it works, lets just get er out there.

**Comment by aaronklaassen** [comment]
@mrmwiebe Yeah I agree. It'll be one of the first things I do post-2.0 though, since it'll make the custom keymap stuff a lot easier.

**Comment by aaronklaassen** [comment]
Ugh now all the problems are in coming back and restoring the Launcher window properly.

Please kill me.

**Pull request merged**
